name: Deploy to Firebase Functions on merge
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.12.2

      - name: Create SA key
        working-directory: functions
        run: mkdir cert && echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > cert/frida-research-firebase-adminsdk-krmnc-3f0287837c.json

      - name: Download node dependencies
        working-directory: functions
        run: npm install

      - name: Download python dependencies
        working-directory: functions
        run: |
          python3.12 -m venv venv
          . venv/bin/activate
          python3.12 -m pip install -r requirements.txt

      - name: Deploy cloud functions
        working-directory: functions
        run: npx firebase-tools deploy
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          API_KEY: ${{ secrets.API_KEY }}
          AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          APP_ID: ${{ secrets.APP_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

