name: Deploy to Firebase Functions on PR
"on":
  push:
    branches:
      - main
env:
  CI: false
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Download node dependencies
        run: npm install

      - name: Create python venv
        working-directory: functions
        run: python -m venv venv

      - name: Download python dependencies
        working-directory: functions
        run: pip install -r requirements.txt

      - name: Activate python venv
        working-directory: functions
        run: source venv/bin/activate

      - name: Deploy
        run: npx firebase-tools deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          API_KEY: ${{ secrets.API_KEY }}
          AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          APP_ID: ${{ secrets.APP_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
